# nvfetcher.toml

[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
fetch.github = "haslersn/any-nix-shell"

[arkenfox-userjs]
src.git = "https://github.com/arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[avizo]
src.git = "https://github.com/misterdanb/avizo"
fetch.github = "misterdanb/avizo"

[awesome]
src.git = "https://github.com/awesomeWM/awesome"
fetch.github = "awesomeWM/awesome"

[awestore]
src.git = "https://github.com/K4rakara/awestore"
fetch.github = "K4rakara/awestore"

[bling]
src.git = "https://github.com/BlingCorp/bling"
fetch.github = "BlingCorp/bling"

[caddy]
src.manual = "b3d35a4995c98cfadeb0c3a356025dbd3984caef"
fetch.github = "caddyserver/caddy"

[cups-pdf]
src.webpage = "https://www.cups-pdf.de/download.shtml"
src.regex = "cups-pdf_(.*)\\.tar\\.gz\">cups-pdf_"
fetch.url = "https://www.cups-pdf.de/src/cups-pdf_$ver.tar.gz"

[dribbblish-dynamic-theme]
src.git = "https://github.com/JulienMaille/dribbblish-dynamic-theme"
fetch.github = "JulienMaille/dribbblish-dynamic-theme"

[droidcam]
src.git = "https://github.com/aramg/droidcam"
fetch.github = "aramg/droidcam"

[eww]
src.git = "https://github.com/elkowar/eww"
src.branch = "config_rework"
fetch.github = "elkowar/eww"
cargo_lock = "Cargo.lock"

[flyingfox]
src.git = "https://github.com/akshat46/FlyingFox"
fetch.github = "akshat46/FlyingFox"

[ibus-bamboo]
src.manual = "v0.7.5-RC2"
fetch.github = "BambooEngine/ibus-bamboo"

[layout-machi]
src.git = "https://github.com/xinhaoyuan/layout-machi"
fetch.github = "xinhaoyuan/layout-machi"

[leonflix]
src.manual = "1.5.50"
fetch.url = "https://leonflix.net/downloads/Leonflix.AppImage"

[libinih]
src.manual = "r53"
fetch.github = "benhoyt/inih"

[lua-pam]
src.git = "https://github.com/RMTT/lua-pam"
fetch.github = "RMTT/lua-pam"

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[microsoft-edge-beta]
src.webpage = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/"
src.regex = "microsoft-edge-beta_(.*)-1_amd64\\.deb\">microsoft-edge-beta_"
fetch.url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_$ver-1_amd64.deb"

[microsoft-edge-dev]
src.webpage = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/"
src.regex = "microsoft-edge-dev_(.*)-1_amd64\\.deb\">microsoft-edge-dev_"
fetch.url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_$ver-1_amd64.deb"

[nix-zsh-completions]
src.git = "https://github.com/Ma27/nix-zsh-completions"
fetch.github = "Ma27/nix-zsh-completions"

[paper]
src.manual = "fc970583d56590fd149b652f12650239fb1d9856"
fetch.git = "https://gitlab.com/snakedye/paper"
cargo_lock = "Cargo.lock"

[picom]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"

[plymouth-themes]
src.git = "https://github.com/adi1090x/plymouth-themes"
fetch.github = "adi1090x/plymouth-themes"

[pure]
src.git = "https://github.com/sindresorhus/pure"
fetch.github = "sindresorhus/pure"

[pywalfox]
src.pypi = "pywalfox"
fetch.pypi = "pywalfox"

[rainfox]
src.git = "https://github.com/1280px/rainfox"
fetch.github = "1280px/rainfox"

[redshift]
src.git = "https://github.com/minus7/redshift"
fetch.github = "minus7/redshift"

[retroarch]
src.git = "https://github.com/libretro/retroarch"
fetch.github = "libretro/retroarch"

[rnix-lsp]
src.git = "https://github.com/nix-community/rnix-lsp"
fetch.github = "nix-community/rnix-lsp"
cargo_lock = "Cargo.lock"

[sddm-chili]
src.git = "https://github.com/MarianArlt/sddm-chili"
fetch.github = "MarianArlt/sddm-chili"

[sf-font-compact]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg"

[sf-font-pro]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg"

[sf-mono]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg"

[ny-font]
src.manual = "0.0.0.20210625"
fetch.url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg"

[spicetify-cli-v1]
src.manual = "v1.2.1"
fetch.github = "khanhas/spicetify-cli"

[spicetify-cli]
src.git = "https://github.com/khanhas/spicetify-cli"
fetch.github = "khanhas/spicetify-cli"

[spicetify-themes]
src.git = "https://github.com/morpheusthewhite/spicetify-themes"
fetch.github = "morpheusthewhite/spicetify-themes"

[spotify]
src.manual = "1.1.56.595.g2d2da0de"
fetch.url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_47.snap"

[steamcompmgr]
src.git = "https://github.com/ChimeraOS/steamos-compositor-plus"
fetch.github = "ChimeraOS/steamos-compositor-plus"

[sway-borders]
src.git = "https://github.com/fluix-dev/sway-borders"
fetch.github = "fluix-dev/sway-borders"

[swaylock-effects]
src.git = "https://github.com/mortie/swaylock-effects"
fetch.github = "mortie/swaylock-effects"

[ventoy]
src.manual = "1.0.46"
fetch.url = "https://github.com/ventoy/Ventoy/releases/download/v$ver/ventoy-$ver-linux.tar.gz"

[whitesur-gtk-theme]
src.git = "https://github.com/vinceliuice/whitesur-gtk-theme"
fetch.github = "vinceliuice/whitesur-gtk-theme"

[whitesur-icon-theme]
src.git = "https://github.com/vinceliuice/whitesur-icon-theme"
fetch.github = "vinceliuice/whitesur-icon-theme"

[widevine-cdm]
src.webpage = "https://dl.google.com/widevine-cdm/versions.txt"
src.regex = "(.*)"
fetch.url = "https://dl.google.com/widevine-cdm/$ver-linux-x64.zip"

[wii-u-gc-adapter]
src.git = "https://github.com/ToadKing/wii-u-gc-adapter"
fetch.github = "ToadKing/wii-u-gc-adapter"

### VS Code Extensions

#### OpenVsx extensions

[awesome-flutter-snippets]
src.openvsx = "Nash.awesome-flutter-snippets"
fetch.openvsx = "Nash.awesome-flutter-snippets"
passthru = { license = "asl20", homepage = "https://github.com/Neevash/awesome-flutter-snippets", description = "Awesome Flutter Snippets is a collection snippets and shortcuts for commonly used Flutter functions and classes" }

[bracket-pair-colorizer-2]
src.openvsx = "CoenraadS.bracket-pair-colorizer-2"
fetch.openvsx = "CoenraadS.bracket-pair-colorizer-2"
passthru = { license = "mit", homepage = "https://github.com/CoenraadS/Bracket-Pair-Colorizer-2", description = "A customizable extension for colorizing matching brackets" }

[codeql]
src.openvsx = "GitHub.vscode-codeql"
fetch.openvsx = "GitHub.vscode-codeql"
passthru = { license = "mit", homepage = "https://github.com/github/vscode-codeql", description = "CodeQL for Visual Studio Code" }

[codesnap]
src.openvsx = "adpyke.codesnap"
fetch.openvsx = "adpyke.codesnap"
passthru = { license = "mit", homepage = "https://github.com/kufii/CodeSnap", description = "📷 Take beautiful screenshots of your code" }

# [cpp]
# src.openvsx = "vscode.cpp"
# fetch.openvsx = "vscode.cpp"
# passthru = { publisher = "vscode", name = "cpp" }

[dart-code]
src.openvsx = "Dart-Code.dart-code"
fetch.openvsx = "Dart-Code.dart-code"
passthru = { license = "mit", homepage = "https://github.com/Dart-Code/Dart-Code", description = "Dart language support and debugger for Visual Studio Code." }

[dendron]
src.openvsx = "dendron.dendron"
fetch.openvsx = "dendron.dendron"
passthru = { license = "agpl3Only", homepage = "https://github.com/dendronhq/dendron", description = "Dendron is a hierarchal note taking tool that grows as you do. " }

[discord-presence]
src.openvsx = "icrawl.discord-vscode"
fetch.openvsx = "icrawl.discord-vscode"
passthru = { license = "mit", homepage = "https://github.com/iCrawl/discord-vscode", description = "Update your discord status with a rich presence." }

[dotenv]
src.openvsx = "mikestead.dotenv"
fetch.openvsx = "mikestead.dotenv"
passthru = { license = "mit", homepage = "https://github.com/mikestead/vscode-dotenv", description = "Support for dotenv file syntax" }

[eslint]
src.openvsx = "dbaeumer.vscode-eslint"
fetch.openvsx = "dbaeumer.vscode-eslint"
passthru = { license = "mit", homepage = "https://github.com/Microsoft/vscode-eslint", description = "Integrates ESLint JavaScript into VS Code." }

[even-better-toml]
src.openvsx = "tamasfe.even-better-toml"
fetch.openvsx = "tamasfe.even-better-toml"
passthru = { license = "mit", homepage = "https://github.com/tamasfe/taplo", description = "Fully-featured TOML support" }

[flutter]
src.openvsx = "Dart-Code.flutter"
fetch.openvsx = "Dart-Code.flutter"
passthru = { license = "mit", homepage = "https://github.com/Dart-Code/Flutter", description = "Flutter support and debugger for Visual Studio Code." }

[gitlens]
src.openvsx = "eamodio.gitlens"
fetch.openvsx = "eamodio.gitlens"
passthru = { license = "mit", homepage = "https://github.com/eamodio/vscode-gitlens", description = "Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more" }

[html-css-class-completion]
src.openvsx = "Zignd.html-css-class-completion"
fetch.openvsx = "Zignd.html-css-class-completion"
passthru = { license = "mit", homepage = "https://github.com/Zignd/HTML-CSS-Class-Completion", description = "CSS class name completion for the HTML class attribute based on the definitions found in your workspace." }

[Kotlin]
src.openvsx = "mathiasfrohlich.Kotlin"
fetch.openvsx = "mathiasfrohlich.Kotlin"
passthru = { license = "asl20", homepage = "https://github.com/mathiasfrohlich/vscode-kotlin", description = "Kotlin language support for VS Code" }

[Material-theme]
src.openvsx = "zhuangtongfa.material-theme"
fetch.openvsx = "zhuangtongfa.material-theme"
passthru = { license = "mit", homepage = "https://github.com/Binaryify/OneDark-Pro", description = "Atom's iconic One Dark theme for Visual Studio Code" }

[markdown-all-in-one]
src.openvsx = "yzhang.markdown-all-in-one"
fetch.openvsx = "yzhang.markdown-all-in-one"
passthru = { license = "mit", homepage = "https://github.com/yzhang-gh/vscode-markdown", description = "All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)" }

[markdown-preview-enhanced]
src.openvsx = "shd101wyy.markdown-preview-enhanced"
fetch.openvsx = "shd101wyy.markdown-preview-enhanced"
passthru = { license = "ncsa", homepage = "https://github.com/shd101wyy/vscode-markdown-preview-enhanced", description = "Markdown Preview Enhanced ported to vscode" }

[material-icon-theme]
src.openvsx = "PKief.material-icon-theme"
fetch.openvsx = "PKief.material-icon-theme"
passthru = { license = "mit", homepage = "https://github.com/PKief/vscode-material-icon-theme", description = "Material Design Icons for Visual Studio Code" }

[nix-env-selector]
src.openvsx = "arrterian.nix-env-selector"
fetch.openvsx = "arrterian.nix-env-selector"
passthru = { license = "mit", homepage = "https://github.com/arrterian/nix-env-selector", description = "Allows switch environment for Visual Studio Code and extensions based on Nix config file." }

[output-colorizer]
src.openvsx = "IBM.output-colorizer"
fetch.openvsx = "IBM.output-colorizer"
passthru = { license = "mit", homepage = "https://github.com/IBM-Bluemix/vscode-log-output-colorizer", description = "Syntax highlighting for log files" }

[prettier]
src.openvsx = "esbenp.prettier-vscode"
fetch.openvsx = "esbenp.prettier-vscode"
passthru = { license = "mit", homepage = "https://github.com/prettier/prettier-vscode", description = "Code formatter using prettier" }

[pubspec-assist]
src.openvsx = "jeroen-meijer.pubspec-assist"
fetch.openvsx = "jeroen-meijer.pubspec-assist"
passthru = { license = "mit", homepage = "https://github.com/jeroen-meijer/pubspec-assist", description = "Easily add and update dependencies to your Dart and Flutter project." }

[python]
src.openvsx = "ms-python.python"
fetch.openvsx = "ms-python.python"
passthru = { license = "mit", homepage = "https://github.com/Microsoft/vscode-python", description = "Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit tests, snippets, and more." }

[rest-client]
src.openvsx = "humao.rest-client"
fetch.openvsx = "humao.rest-client"
passthru = { license = "mit", homepage = "https://github.com/Huachao/vscode-restclient", description = "REST Client for Visual Studio Code" }

[rust]
src.openvsx = "rust-lang.rust"
fetch.openvsx = "rust-lang.rust"
passthru = { license = '[ "mit", "asl20" ]', homepage = "https://github.com/rust-lang/rls-vscode", description = "Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer). Provides lints, code completion and navigation, formatting and more." }

[svelte]
src.openvsx = "svelte.svelte-vscode"
fetch.openvsx = "svelte.svelte-vscode"
passthru = { license = "mit", homepage = "https://github.com/sveltejs/language-tools", description = "Svelte language support for VS Code" }

[tailwindcss]
src.openvsx = "bradlc.vscode-tailwindcss"
fetch.openvsx = "bradlc.vscode-tailwindcss"
passthru = { license = "mit", homepage = "https://github.com/tailwindlabs/tailwindcss-intellisense", description = "Intelligent Tailwind CSS tooling for VS Code" }

[versionlens]
src.openvsx = "pflannery.vscode-versionlens"
fetch.openvsx = "pflannery.vscode-versionlens"
passthru = { license = "isc", homepage = "https://gitlab.com/versionlens/vscode-versionlens", description = "Shows the latest version for each package using code lens" }

#### VsMarketplace extensions

[ActiveFileInStatusBar]
src.vsmarketplace = "RoscoP.ActiveFileInStatusBar"
fetch.vsmarketplace = "RoscoP.ActiveFileInStatusBar"
passthru = { license = "mit" }

[astro]
src.vsmarketplace = "astro-build.astro-vscode"
fetch.vsmarketplace = "astro-build.astro-vscode"
passthru = { license = "mit" }

[css-initial-value]
src.vsmarketplace = "dzhavat.css-initial-value"
fetch.vsmarketplace = "dzhavat.css-initial-value"
passthru = { license = "mit" }

[nixpkgs-fmt]
src.vsmarketplace = "B4dM4n.nixpkgs-fmt"
fetch.vsmarketplace = "B4dM4n.nixpkgs-fmt"
passthru = { license = "mit" }

[pascal]
src.vsmarketplace = "alefragnani.pascal"
fetch.vsmarketplace = "alefragnani.pascal"
passthru = { license = "mit" }

[pascal-formatter]
src.vsmarketplace = "alefragnani.pascal-formatter"
fetch.vsmarketplace = "alefragnani.pascal-formatter"
passthru = { license = "mit" }

[react-native]
src.vsmarketplace = "msjsdiag.vscode-react-native"
fetch.vsmarketplace = "msjsdiag.vscode-react-native"
passthru = { license = "mit" }
