#!/usr/bin/env sh

read -r -d '' POWER << EOM
<box orientation="v" spacing="10" space-evenly="false">
<box space-evenly="false" style="margin: 10px 5px 5px 5px;padding: 0px"
orientation="v" halign="fill" spacing="10">
  <box class="power" orientation="h" halign="center" valign="center" width="50" height="70" style="font-size: 40px;margin: 5px" spacing="10">
    <button onclick="swaylock -f; ~/.local/bin/toggle notification">\uf83d</button>
    <button onclick="systemctl suspend; ~/.local/bin/toggle notification">\uf9b1</button>
    <button onclick="loginctl terminate-user $USER">\uf705</button>
    <button onclick="systemctl poweroff">\u23fb</button>
  </box>
</box>
EOM

~/.local/bin/eww update content="$POWER"

~/.local/bin/toggle notification
