[tailscale]
suffix = "beta.tailscale.net"
nameserver = "danielphan-2003.gmail.com.beta.tailscale.net"

[hosts.themachine]
gateway = "192.168.1.1"
ip_addr = "192.168.1.11"

[hosts.pik2]
gateway = "192.168.1.1"
ip_addr = "192.168.1.2"
