[tailscale]
nameserver = "danielphan-2003.gmail.com.beta.tailscale.net"

[hosts.themachine]
# irrelevant now that it uses Tailscale
ip_addr = "192.168.1.11"

[hosts.pik2]
# irrelevant now that it uses Tailscale
ip_addr = "192.168.1.2"
