#!/usr/bin/env sh

pamixer --toggle-mute

MUTED=$(eww state | grep muted | awk '{print $2}')

if $MUTED; then
  eww update muted=false
else
  eww update muted=true
fi

~/.config/eww/scripts/volume $(pamixer --get-volume)
