{ lib, config, ... }: {
  imports = [ ../resolved ];

  networking.firewall.allowedUDPPorts = [ 53 ];

  networking.nameservers = lib.mkDefault config.services.resolved.fallbackDns;

  environment.etc."resolv.conf".text = ''
    # Generated by NixOS
    ${lib.concatMapStrings (x: "search ${x}\n") config.networking.search}
    ${lib.concatMapStrings (x: "nameserver ${x}\n") config.networking.nameservers}
    options edns0
  '';

  # systemd-resolved is the default dns server, but for others to work it needs to be disabled
  services.resolved.enable = false;
}
