# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
    src = fetchgit {
      url = "https://github.com/haslersn/any-nix-shell";
      rev = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0q27rhjhh7k0qgcdcfm8ly5za6wm4rckh633d0sjz87faffkp90k";
    };

  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "b761a9dd32f79395b0fca183ad8fe45f7e99d26f";
    src = fetchgit {
      url = "https://github.com/arkenfox/user.js";
      rev = "b761a9dd32f79395b0fca183ad8fe45f7e99d26f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19mgz74cz9bl3vffcl9f351qbzwdjd5qmkqacd0brk9kvnbvmvp3";
    };

  };
  avizo = {
    pname = "avizo";
    version = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
    src = fetchgit {
      url = "https://github.com/misterdanb/avizo";
      rev = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11sr6ckvrsv6f29ja6f20xw4j1ml2y01mfg2yrsxin7n0641s44b";
    };

  };
  awesome = {
    pname = "awesome";
    version = "f473639c5d36358a260be383888e34ac42859ad3";
    src = fetchgit {
      url = "https://github.com/awesomeWM/awesome";
      rev = "f473639c5d36358a260be383888e34ac42859ad3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0jjjf6xfva3vppb098kp15m1i60da99v79xsh31qzy3d925f95sg";
    };

  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchgit {
      url = "https://github.com/K4rakara/awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1sirj1cy38v3sg673wy0yphk0vk19qhlzavp53bjf2jvzq8jdqsn";
    };

  };
  bling = {
    pname = "bling";
    version = "921d386b47a23e44509631b772670bb68de6164a";
    src = fetchgit {
      url = "https://github.com/BlingCorp/bling";
      rev = "921d386b47a23e44509631b772670bb68de6164a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1nrg1rfgvqsz3dqky65kfam11hcsslj7zkr7rmwl0824xs7s8b7r";
    };

  };
  caddy = {
    pname = "caddy";
    version = "b3d35a4995c98cfadeb0c3a356025dbd3984caef";
    src = fetchgit {
      url = "https://github.com/caddyserver/caddy";
      rev = "b3d35a4995c98cfadeb0c3a356025dbd3984caef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0bs92d2y28q8jxvrxd87b7icq06794k5idm1qmh0xqn9f7la0zqv";
    };

  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      sha256 = "0ccmm9crrm07nqzn4aikbys2bflkgzc044j1bvz6j53zzznnk1kk";
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
    };

  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "fa97b3f611612abd4b48d898ebbd7751da5b6f29";
    src = fetchgit {
      url = "https://github.com/JulienMaille/dribbblish-dynamic-theme";
      rev = "fa97b3f611612abd4b48d898ebbd7751da5b6f29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "164f3bc6hkx5grzvqs3j44ng7v3g6ajc7nkz8insl06z3l002jaj";
    };

  };
  droidcam = {
    pname = "droidcam";
    version = "718e575ca2895cec30364cf75ea252832d9d2c86";
    src = fetchgit {
      url = "https://github.com/aramg/droidcam";
      rev = "718e575ca2895cec30364cf75ea252832d9d2c86";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1filw83mslg1anfw43bl5nd81l8fr2rnf4sg868wqrilbcgsppbi";
    };

  };
  flyingfox = {
    pname = "flyingfox";
    version = "8fc00aa654c10260deac2cbbc5bf062b7dcce811";
    src = fetchgit {
      url = "https://github.com/akshat46/FlyingFox";
      rev = "8fc00aa654c10260deac2cbbc5bf062b7dcce811";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0z6q2953cbxngnzbpd0map2r89dywg3xjagav1qzzbpkyqck32w9";
    };

  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "v0.7.5-RC2";
    src = fetchgit {
      url = "https://github.com/BambooEngine/ibus-bamboo";
      rev = "v0.7.5-RC2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0ra548xlnmf1fdxah23ic5gbdmfdky41piramzfpgmhafxfggz8p";
    };

  };
  layout-machi = {
    pname = "layout-machi";
    version = "7f5b0b17a5e56ec3ad58d5b7ba33bda0ee38ddc1";
    src = fetchgit {
      url = "https://github.com/xinhaoyuan/layout-machi";
      rev = "7f5b0b17a5e56ec3ad58d5b7ba33bda0ee38ddc1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11r9hh79xg8c0kaa8j3qmni9qsi59sm1rs1smy5k2ll0iy8zpw7w";
    };

  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      sha256 = "0bhyccmd4217p2ndh12lz4dy4cjhgvkm4ml5r32nhxgxycw3r28n";
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
    };

  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchgit {
      url = "https://github.com/benhoyt/inih";
      rev = "r53";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0dqf5j2sw4hq68rqvxbrsf44ygfzx9ypiyzipk4cvp9aimbvsbc6";
    };

  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchgit {
      url = "https://github.com/RMTT/lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g5n055gj2ii1pxjfykn3xr0q9knl4hbk0irylsip0r6r76jhz9a";
    };

  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };

  };
  meson = {
    pname = "meson";
    version = "0.58.1";
    src = fetchurl {
      sha256 = "0padn0ykwz8azqiwkhi8p97bl742y8lsjbv0wpqpkkrgcvda6i1i";
      url = "https://pypi.io/packages/source/m/meson/meson-0.58.1.tar.gz";
    };

  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "92.0.902.40";
    src = fetchurl {
      sha256 = "17izpgvp5irxzsa0miszla1xd9zi94f8lh6y8y1d7ddl481q7khj";
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_92.0.902.40-1_amd64.deb";
    };

  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "93.0.933.1";
    src = fetchurl {
      sha256 = "0bn7r163dg3lh7y67mkijqiz8b387bfms4knizaa80j7y432f645";
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_93.0.933.1-1_amd64.deb";
    };

  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchgit {
      url = "https://github.com/Ma27/nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "16r0l7c1jp492977p8k6fcw2jgp6r43r85p6n3n1a53ym7kjhs2d";
    };

  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1cpk6ysrj346wmm89kd35w2fv8y5z136948fll06ib3mxh1gljp4";
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
    };

  };
  picom = {
    pname = "picom";
    version = "e92403bd67f44d8bae4fa5b2eb6a2617fe12b7a6";
    src = fetchgit {
      url = "https://github.com/yshui/picom";
      rev = "e92403bd67f44d8bae4fa5b2eb6a2617fe12b7a6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0xx2qv722wjlxdcs4knm5s11c895hsf2bjhbkz1v3q84yrhyzyfl";
    };

  };
  pure = {
    pname = "pure";
    version = "c05916f3870e2a856607fe6d6ad0cd7fe9b270a8";
    src = fetchgit {
      url = "https://github.com/sindresorhus/pure";
      rev = "c05916f3870e2a856607fe6d6ad0cd7fe9b270a8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0l3q44ybp84bikqcgx4187cm5qfdb0a0mzh5bbw95hyil0g8qg5a";
    };

  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      sha256 = "0rpdh1k4b37n0gcclr980vz9pw3ihhyy0d0nh3xp959q4xz3vrsr";
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
    };

  };
  rainfox = {
    pname = "rainfox";
    version = "d373dc136b805097f5092d02365a90327dc1de4a";
    src = fetchgit {
      url = "https://github.com/1280px/rainfox";
      rev = "d373dc136b805097f5092d02365a90327dc1de4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1g39n3gzqq4hgic3w4n20fs8cz4a855scbnmah8pypz3amsnqzr5";
    };

  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchgit {
      url = "https://github.com/minus7/redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0nbkcw3avmzjg1jr1g9yfpm80kzisy55idl09b6wvzv2sz27n957";
    };

  };
  retroarch = {
    pname = "retroarch";
    version = "0570ed4ca3e02449a1a95bf26a73c3de3bf1aff7";
    src = fetchgit {
      url = "https://github.com/libretro/retroarch";
      rev = "0570ed4ca3e02449a1a95bf26a73c3de3bf1aff7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0xirrjl7ynvxvkl0xnbaycdn55l5v95zlyy9f7948bh460y9rw1k";
    };

  };
  rnix-lsp = {
    pname = "rnix-lsp";
    version = "55838bd432a7f4c79a33464bf76c73886226d38c";
    src = fetchgit {
      url = "https://github.com/nix-community/rnix-lsp";
      rev = "55838bd432a7f4c79a33464bf76c73886226d38c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g7562v9hz97x0fmg5d9rw57vls0d7m3kzc9ypys97y2sqy14w4f";
    };

  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchgit {
      url = "https://github.com/MarianArlt/sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "036fxsa7m8ymmp3p40z671z163y6fcsa9a641lrxdrw225ssq5f3";
    };

  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1wklslljf8pz3aj2lyzrnqmqyydgdwmn5ywnpssrb2r4fkb7swak";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
    };

  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1wy3v2c87cpd9w333w78s6nn7fl5cnbsv8wff01xml6m3wgl7brz";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
    };

  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "04gznp6ynn2p67a1lgb5zgs5j4v6gcz8xh94p6f2yzbr23iih1gc";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
    };

  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "242bde5afa936dcdc69efefb2d20c5e8b504e474";
    src = fetchgit {
      url = "https://github.com/khanhas/spicetify-cli";
      rev = "242bde5afa936dcdc69efefb2d20c5e8b504e474";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "00v0f2hxa8mxdpgf3y53dc9cfgp63cx4bcqsh69m6cs76hsmz7rn";
    };

  };
  spicetify-cli-v1 = {
    pname = "spicetify-cli-v1";
    version = "v1.2.1";
    src = fetchgit {
      url = "https://github.com/khanhas/spicetify-cli";
      rev = "v1.2.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1sp482rfwxqgb3mi9m84bjk9cakvc1l7gr498d80vz56z9l8a10w";
    };

  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "f3daef1d1fae1dfff3c0486e8b6fdc554dca69d6";
    src = fetchgit {
      url = "https://github.com/morpheusthewhite/spicetify-themes";
      rev = "f3daef1d1fae1dfff3c0486e8b6fdc554dca69d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0km6a3fp7y1b7m5s4504ig5kn3fmn8j33dzyp3piw2f1m36j4z4z";
    };

  };
  spotify = {
    pname = "spotify";
    version = "1.1.56.595.g2d2da0de";
    src = fetchurl {
      sha256 = "1rghjxj0y0wnmyzbdd2dp7z2skhp153qnl8cqp309gsxx1iiwv5c";
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_47.snap";
    };

  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "f8acefeb3ffaab4250fb98127ee08ffb4a7fb84d";
    src = fetchgit {
      url = "https://github.com/ChimeraOS/steamos-compositor-plus";
      rev = "f8acefeb3ffaab4250fb98127ee08ffb4a7fb84d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0pn5phqv4a2vhmslfcidhrjxwx2yih7bfsavxgqs6a4m5hqbmmd6";
    };

  };
  sway-borders = {
    pname = "sway-borders";
    version = "72d4033bc803a786987cc0b9c58da964513d77ba";
    src = fetchgit {
      url = "https://github.com/fluix-dev/sway-borders";
      rev = "72d4033bc803a786987cc0b9c58da964513d77ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "03rzrw710sv9vbl3fhh70n5ypg4jbc7p01p0ys4q1wil1ss7ffj1";
    };

  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      sha256 = "1gn4a5j57fwbs3afsv7vmm71kkism6r0rhmngffgk3j1j3lk450p";
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
    };

  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "a3b0c1b47060062b7dde4a4311694beb3b26280f";
    src = fetchgit {
      url = "https://github.com/vinceliuice/whitesur-gtk-theme";
      rev = "a3b0c1b47060062b7dde4a4311694beb3b26280f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b75s8g2vk36v99zgjk4hyp3agwbwky9vaprqij6w9ncci0fp4mb";
    };

  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "5524cca7099ec4c9b485a024d91e27d04a38e0b6";
    src = fetchgit {
      url = "https://github.com/vinceliuice/whitesur-icon-theme";
      rev = "5524cca7099ec4c9b485a024d91e27d04a38e0b6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1wblj062250g5xr59p1c80jzlidc5bm2v0b4ikjh4adac25x5n68";
    };

  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2209.1";
    src = fetchurl {
      sha256 = "1mnbxkazjyl3xgvpna9p9qiiyf08j4prdxry51wk8jj5ns6c2zcc";
      url = "https://dl.google.com/widevine-cdm/4.10.2209.1-linux-x64.zip";
    };

  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "64d7ddc511adb12f2eb05bd97294bc51cf51bfab";
    src = fetchgit {
      url = "https://github.com/ToadKing/wii-u-gc-adapter";
      rev = "64d7ddc511adb12f2eb05bd97294bc51cf51bfab";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1rjqjc344j6lvs6ya5m34i4hv5296xfdxr8pc2bgas46gxhv7336";
    };

  };
}
