# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
    src = fetchgit {
      url = "https://github.com/haslersn/any-nix-shell";
      rev = "ea04f9bd639f175002127ad1b5715bce3d4bd9c5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0q27rhjhh7k0qgcdcfm8ly5za6wm4rckh633d0sjz87faffkp90k";
    };
  };
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "b761a9dd32f79395b0fca183ad8fe45f7e99d26f";
    src = fetchgit {
      url = "https://github.com/arkenfox/user.js";
      rev = "b761a9dd32f79395b0fca183ad8fe45f7e99d26f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19mgz74cz9bl3vffcl9f351qbzwdjd5qmkqacd0brk9kvnbvmvp3";
    };
  };
  avizo = {
    pname = "avizo";
    version = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
    src = fetchgit {
      url = "https://github.com/misterdanb/avizo";
      rev = "7b3874e5ee25c80800b3c61c8ea30612aaa6e8d1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "11sr6ckvrsv6f29ja6f20xw4j1ml2y01mfg2yrsxin7n0641s44b";
    };
  };
  awesome = {
    pname = "awesome";
    version = "832483dd60ba194f3ae0200ab39a3a548c26e910";
    src = fetchgit {
      url = "https://github.com/awesomeWM/awesome";
      rev = "832483dd60ba194f3ae0200ab39a3a548c26e910";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1bcbxsiydlz439af6dq69z8g7rca4jganlz65f3ajrlgqknk86cq";
    };
  };
  awestore = {
    pname = "awestore";
    version = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
    src = fetchgit {
      url = "https://github.com/K4rakara/awestore";
      rev = "5509786a1d5bc538dcdde027bd07b35bc29b0df1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1sirj1cy38v3sg673wy0yphk0vk19qhlzavp53bjf2jvzq8jdqsn";
    };
  };
  bling = {
    pname = "bling";
    version = "9104455fff48fa80aaa5425d50fbb3b7ad2e7cdd";
    src = fetchgit {
      url = "https://github.com/BlingCorp/bling";
      rev = "9104455fff48fa80aaa5425d50fbb3b7ad2e7cdd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "09r1njzz8qghr0py0sypygrqw77qg9r3grp67jc8w2y954mhwznh";
    };
  };
  caddy = {
    pname = "caddy";
    version = "b3d35a4995c98cfadeb0c3a356025dbd3984caef";
    src = fetchgit {
      url = "https://github.com/caddyserver/caddy";
      rev = "b3d35a4995c98cfadeb0c3a356025dbd3984caef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0bs92d2y28q8jxvrxd87b7icq06794k5idm1qmh0xqn9f7la0zqv";
    };
  };
  cups-pdf = {
    pname = "cups-pdf";
    version = "3.0.1";
    src = fetchurl {
      sha256 = "0ccmm9crrm07nqzn4aikbys2bflkgzc044j1bvz6j53zzznnk1kk";
      url = "https://www.cups-pdf.de/src/cups-pdf_3.0.1.tar.gz";
    };
  };
  dribbblish-dynamic-theme = {
    pname = "dribbblish-dynamic-theme";
    version = "fa97b3f611612abd4b48d898ebbd7751da5b6f29";
    src = fetchgit {
      url = "https://github.com/JulienMaille/dribbblish-dynamic-theme";
      rev = "fa97b3f611612abd4b48d898ebbd7751da5b6f29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "164f3bc6hkx5grzvqs3j44ng7v3g6ajc7nkz8insl06z3l002jaj";
    };
  };
  droidcam = {
    pname = "droidcam";
    version = "718e575ca2895cec30364cf75ea252832d9d2c86";
    src = fetchgit {
      url = "https://github.com/aramg/droidcam";
      rev = "718e575ca2895cec30364cf75ea252832d9d2c86";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1filw83mslg1anfw43bl5nd81l8fr2rnf4sg868wqrilbcgsppbi";
    };
  };
  flyingfox = {
    pname = "flyingfox";
    version = "8fc00aa654c10260deac2cbbc5bf062b7dcce811";
    src = fetchgit {
      url = "https://github.com/akshat46/FlyingFox";
      rev = "8fc00aa654c10260deac2cbbc5bf062b7dcce811";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0z6q2953cbxngnzbpd0map2r89dywg3xjagav1qzzbpkyqck32w9";
    };
  };
  ibus-bamboo = {
    pname = "ibus-bamboo";
    version = "v0.7.5-RC2";
    src = fetchgit {
      url = "https://github.com/BambooEngine/ibus-bamboo";
      rev = "v0.7.5-RC2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0ra548xlnmf1fdxah23ic5gbdmfdky41piramzfpgmhafxfggz8p";
    };
  };
  layout-machi = {
    pname = "layout-machi";
    version = "5cee31af77493a67516ca27252c3d931efbfcac7";
    src = fetchgit {
      url = "https://github.com/xinhaoyuan/layout-machi";
      rev = "5cee31af77493a67516ca27252c3d931efbfcac7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1a9rfhfd4gw7nhcxm873vhanbcgqshq9wjnrpz908jxpk4bw64b3";
    };
  };
  leonflix = {
    pname = "leonflix";
    version = "1.5.50";
    src = fetchurl {
      sha256 = "0bhyccmd4217p2ndh12lz4dy4cjhgvkm4ml5r32nhxgxycw3r28n";
      url = "https://leonflix.net/downloads/Leonflix.AppImage";
    };
  };
  libinih = {
    pname = "libinih";
    version = "r53";
    src = fetchgit {
      url = "https://github.com/benhoyt/inih";
      rev = "r53";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0dqf5j2sw4hq68rqvxbrsf44ygfzx9ypiyzipk4cvp9aimbvsbc6";
    };
  };
  lua-pam = {
    pname = "lua-pam";
    version = "482071137257e55dac62a510f792104a9d910ea1";
    src = fetchgit {
      url = "https://github.com/RMTT/lua-pam";
      rev = "482071137257e55dac62a510f792104a9d910ea1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g5n055gj2ii1pxjfykn3xr0q9knl4hbk0irylsip0r6r76jhz9a";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  microsoft-edge-beta = {
    pname = "microsoft-edge-beta";
    version = "92.0.902.49";
    src = fetchurl {
      sha256 = "1gbnlyy8qpl7asjyfp3qbr74ai4a8aw0abm5620dxkli395ny8v2";
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_92.0.902.49-1_amd64.deb";
    };
  };
  microsoft-edge-dev = {
    pname = "microsoft-edge-dev";
    version = "93.0.946.1";
    src = fetchurl {
      sha256 = "10nhbzmxxgpyag6faziss4s90hk9spm2ckfsavypkj01y62zr6md";
      url = "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_93.0.946.1-1_amd64.deb";
    };
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
    src = fetchgit {
      url = "https://github.com/Ma27/nix-zsh-completions";
      rev = "468d8cf752a62b877eba1a196fbbebb4ce4ebb6f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "16r0l7c1jp492977p8k6fcw2jgp6r43r85p6n3n1a53ym7kjhs2d";
    };
  };
  ny-font = {
    pname = "ny-font";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1cpk6ysrj346wmm89kd35w2fv8y5z136948fll06ib3mxh1gljp4";
      url = "https://devimages-cdn.apple.com/design/resources/download/NY.dmg";
    };
  };
  paper = {
    pname = "paper";
    version = "d6df912618ce751dcfeac96b905865d954babbc6";
    src = fetchgit {
      url = "https://gitlab.com/snakedye/paper.git";
      rev = "d6df912618ce751dcfeac96b905865d954babbc6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0mb84vkvnfmw071mgnryvgpvyckvs2421pssblb491rv4fqaw180";
    };
    cargoLock = {
      lockFile = ./paper-d6df912618ce751dcfeac96b905865d954babbc6/Cargo.lock;
      outputHashes = {
        "snui-0.1.0" = "1fkcjj4121gbl6xsmhqb02cbvwqdfl3l9q7bnivl817v88pgs69f";
      };
    };
  };
  picom = {
    pname = "picom";
    version = "057a939431a5e856d001a5b2be9b9ba86738e829";
    src = fetchgit {
      url = "https://github.com/yshui/picom";
      rev = "057a939431a5e856d001a5b2be9b9ba86738e829";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "01apbg9z4195623j5pi2xrc0aqaffkxpkrf8j53rbyi5xlg9i5gx";
    };
  };
  plymouth-themes = {
    pname = "plymouth-themes";
    version = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
    src = fetchgit {
      url = "https://github.com/adi1090x/plymouth-themes";
      rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0scgba00f6by08hb14wrz26qcbcysym69mdlv913mhm3rc1szlal";
    };
  };
  pure = {
    pname = "pure";
    version = "f4c6d79ba2417d63c8008b6acce628631fd462ec";
    src = fetchgit {
      url = "https://github.com/sindresorhus/pure";
      rev = "f4c6d79ba2417d63c8008b6acce628631fd462ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0qfs7rvpyd8jb7x4ziqrkh0b6g9ldds8sn6qbqgrir80vdk90gpa";
    };
  };
  pywalfox = {
    pname = "pywalfox";
    version = "2.7.4";
    src = fetchurl {
      sha256 = "0rpdh1k4b37n0gcclr980vz9pw3ihhyy0d0nh3xp959q4xz3vrsr";
      url = "https://pypi.io/packages/source/p/pywalfox/pywalfox-2.7.4.tar.gz";
    };
  };
  rainfox = {
    pname = "rainfox";
    version = "d373dc136b805097f5092d02365a90327dc1de4a";
    src = fetchgit {
      url = "https://github.com/1280px/rainfox";
      rev = "d373dc136b805097f5092d02365a90327dc1de4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1g39n3gzqq4hgic3w4n20fs8cz4a855scbnmah8pypz3amsnqzr5";
    };
  };
  redshift = {
    pname = "redshift";
    version = "7da875d34854a6a34612d5ce4bd8718c32bec804";
    src = fetchgit {
      url = "https://github.com/minus7/redshift";
      rev = "7da875d34854a6a34612d5ce4bd8718c32bec804";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0nbkcw3avmzjg1jr1g9yfpm80kzisy55idl09b6wvzv2sz27n957";
    };
  };
  retroarch = {
    pname = "retroarch";
    version = "e5bbd9488f80694afdf40c19bedf492569f8d4f3";
    src = fetchgit {
      url = "https://github.com/libretro/retroarch";
      rev = "e5bbd9488f80694afdf40c19bedf492569f8d4f3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0lqfrqydy2a66jd5vm8cfv7amvw8cf6wmay2pr9hfhjjy47q3d8r";
    };
  };
  rnix-lsp = {
    pname = "rnix-lsp";
    version = "55838bd432a7f4c79a33464bf76c73886226d38c";
    src = fetchgit {
      url = "https://github.com/nix-community/rnix-lsp";
      rev = "55838bd432a7f4c79a33464bf76c73886226d38c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0g7562v9hz97x0fmg5d9rw57vls0d7m3kzc9ypys97y2sqy14w4f";
    };
    cargoLock = {
      lockFile = ./rnix-lsp-55838bd432a7f4c79a33464bf76c73886226d38c/Cargo.lock;
      outputHashes = { };
    };
  };
  sddm-chili = {
    pname = "sddm-chili";
    version = "6516d50176c3b34df29003726ef9708813d06271";
    src = fetchgit {
      url = "https://github.com/MarianArlt/sddm-chili";
      rev = "6516d50176c3b34df29003726ef9708813d06271";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "036fxsa7m8ymmp3p40z671z163y6fcsa9a641lrxdrw225ssq5f3";
    };
  };
  sf-font-compact = {
    pname = "sf-font-compact";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1wklslljf8pz3aj2lyzrnqmqyydgdwmn5ywnpssrb2r4fkb7swak";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg";
    };
  };
  sf-font-pro = {
    pname = "sf-font-pro";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "1wy3v2c87cpd9w333w78s6nn7fl5cnbsv8wff01xml6m3wgl7brz";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg";
    };
  };
  sf-mono = {
    pname = "sf-mono";
    version = "0.0.0.20210625";
    src = fetchurl {
      sha256 = "04gznp6ynn2p67a1lgb5zgs5j4v6gcz8xh94p6f2yzbr23iih1gc";
      url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg";
    };
  };
  spicetify-cli = {
    pname = "spicetify-cli";
    version = "242bde5afa936dcdc69efefb2d20c5e8b504e474";
    src = fetchgit {
      url = "https://github.com/khanhas/spicetify-cli";
      rev = "242bde5afa936dcdc69efefb2d20c5e8b504e474";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "00v0f2hxa8mxdpgf3y53dc9cfgp63cx4bcqsh69m6cs76hsmz7rn";
    };
  };
  spicetify-cli-v1 = {
    pname = "spicetify-cli-v1";
    version = "v1.2.1";
    src = fetchgit {
      url = "https://github.com/khanhas/spicetify-cli";
      rev = "v1.2.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1sp482rfwxqgb3mi9m84bjk9cakvc1l7gr498d80vz56z9l8a10w";
    };
  };
  spicetify-themes = {
    pname = "spicetify-themes";
    version = "691a069fe03933695abadaa53ae5c624564ad5b6";
    src = fetchgit {
      url = "https://github.com/morpheusthewhite/spicetify-themes";
      rev = "691a069fe03933695abadaa53ae5c624564ad5b6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0w3wgfiwq00yr2iam7bx7a7ai7s5fvlvril8gl2g7v84i20cadis";
    };
  };
  spotify = {
    pname = "spotify";
    version = "1.1.56.595.g2d2da0de";
    src = fetchurl {
      sha256 = "1rghjxj0y0wnmyzbdd2dp7z2skhp153qnl8cqp309gsxx1iiwv5c";
      url = "https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_47.snap";
    };
  };
  steamcompmgr = {
    pname = "steamcompmgr";
    version = "f8acefeb3ffaab4250fb98127ee08ffb4a7fb84d";
    src = fetchgit {
      url = "https://github.com/ChimeraOS/steamos-compositor-plus";
      rev = "f8acefeb3ffaab4250fb98127ee08ffb4a7fb84d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0pn5phqv4a2vhmslfcidhrjxwx2yih7bfsavxgqs6a4m5hqbmmd6";
    };
  };
  sway-borders = {
    pname = "sway-borders";
    version = "c28185ab0603a3c82778797d158b391f843e3537";
    src = fetchgit {
      url = "https://github.com/fluix-dev/sway-borders";
      rev = "c28185ab0603a3c82778797d158b391f843e3537";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "10bcknyp3drdqgfpimka1sj0cljxifp32j4dddq4s8s4v8d1dbjh";
    };
  };
  swaylock-effects = {
    pname = "swaylock-effects";
    version = "5cb9579faaf5662b111f5722311b701eff1c1d00";
    src = fetchgit {
      url = "https://github.com/mortie/swaylock-effects";
      rev = "5cb9579faaf5662b111f5722311b701eff1c1d00";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "036dkhfqgk7g9vbr5pxgrs66h5fz0rwdsc67i1w51aa9v01r35ca";
    };
  };
  ventoy = {
    pname = "ventoy";
    version = "1.0.46";
    src = fetchurl {
      sha256 = "1gn4a5j57fwbs3afsv7vmm71kkism6r0rhmngffgk3j1j3lk450p";
      url = "https://github.com/ventoy/Ventoy/releases/download/v1.0.46/ventoy-1.0.46-linux.tar.gz";
    };
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "3f0490ab7affe106445ae269c4597d6327f1aa9c";
    src = fetchgit {
      url = "https://github.com/vinceliuice/whitesur-gtk-theme";
      rev = "3f0490ab7affe106445ae269c4597d6327f1aa9c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0qqdrkw7qjbl1sy9v94ynv02drp70y114hxbpa4ak2kl3ww4xyya";
    };
  };
  whitesur-icon-theme = {
    pname = "whitesur-icon-theme";
    version = "4269b1790c3c09974e3a0f5b855a46739a1ddde7";
    src = fetchgit {
      url = "https://github.com/vinceliuice/whitesur-icon-theme";
      rev = "4269b1790c3c09974e3a0f5b855a46739a1ddde7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "10wsbnjd287053msbxs1a4bn46f0zvbq79bj9j0kbqxyh48v1gg7";
    };
  };
  widevine-cdm = {
    pname = "widevine-cdm";
    version = "4.10.2209.1";
    src = fetchurl {
      sha256 = "1mnbxkazjyl3xgvpna9p9qiiyf08j4prdxry51wk8jj5ns6c2zcc";
      url = "https://dl.google.com/widevine-cdm/4.10.2209.1-linux-x64.zip";
    };
  };
  wii-u-gc-adapter = {
    pname = "wii-u-gc-adapter";
    version = "64d7ddc511adb12f2eb05bd97294bc51cf51bfab";
    src = fetchgit {
      url = "https://github.com/ToadKing/wii-u-gc-adapter";
      rev = "64d7ddc511adb12f2eb05bd97294bc51cf51bfab";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1rjqjc344j6lvs6ya5m34i4hv5296xfdxr8pc2bgas46gxhv7336";
    };
  };
}
